dist: trusty
sudo: false
language:
- node_js
node_js:
- '7'
env:
- TERM=dumb
install:
- cd web && npm run init
- cd ../bundles && ./gradlew --version
script:
- cd ../web && npm run build-prod
- cd ..
after_success:
- git status
cache:
  directories:
  - cnf/cache/stable

addons:
  sonarcloud:
    organization: "fswt-github" # the key of the org you chose at step #3
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner \
  -Dsonar.projectKey=fswt_specmate \
  -Dsonar.sources=./web/src
