sudo: false
language:
- node_js
node_js:
- '7'
env:
- TERM=dumb
install:
- cd web && npm run init
- cd ../bundles && ./gradlew --version
script:
- cd ../web && npm run build-prod
- cd ..
after_success:
- git status
cache:
  directories:
  - cnf/cache/stable
